version: "3.6"

services:
  dev:
    image: odytrice/workspace:python
    network_mode: host

    environment:
      DockerHost: host.docker.internal
    volumes:
      - ..:/workspace:Z,cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/:/root/.ssh

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity